name: CommandBlocker
version: '${project.version}'
main: org.commandblocker.CommandBlocker
api-version: 1.13
authors: [YF_Eternal]
description: Organization uses commands outside of whitelist.
commands:
  commandblocker:
    description: Main plugin command.
    aliases: [cb]

permissions:
  commandblocker.admin:
    description: Gives the player access to the main plugin command.
    default: op
  commandblocker.*:
    description: Gives the player all plugin permissions.
    default: false
    children:
      commandblocker.admin: true